### PR TITLE
Add CRC-32C checksum to sharded index format

### PR DESCRIPTION
**Pull request by jbms**

### CODE REVIEW

**Comment by jbms** [comment]
I also clarified the language a bit to account for the possibility of nested sharding.

**Comment by jbms** [comment]
@normanz Your input would be much appreciated.

**Review by normanrz — APPROVED** [review]
LGTM :+1:

**Comment by clbarnes** [comment]
Worth combining this with a spec for a CRC-32C bytes->bytes codec to apply to chunks too? Seems like low-hanging fruit if we're pulling in that functionality anyway.

**Comment by jbms** [comment]
I agree it makes sense to add a crc32c bytes->bytes codec, but I would just assume address that in a separate PR.

**Review by jstriebel — APPROVED** [review]
LGTM, thanks :+1:

**Pull request merged**
