### PR TITLE
Core protocol v3.0 - array and group metadata

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has a straw man for a section on array and group metadata.

### CODE REVIEW

**Comment by alimanfoo** [comment]
This is still WIP but thought I'd surface to give a sense of direction of travel. Comments welcome.

**Comment by alimanfoo** [comment]
Did a bit of refactoring and added in a subsection about group metadata.

**Comment by alimanfoo** [comment]
One change I've tentatively pushed is to allow for inclusion of "user attributes" within the array and group metadata documents, a la n5, rather than in separate documents a la zarr v2.

**Comment by alimanfoo** [comment]
In the interests of having content together in one place, I'd like to merge this PR into the core-protocol-v3.0-dev branch. We can still discuss, revise and revisit anything after merge. I'll merge tomorrow if no objections.

**Comment by joshmoore** [comment]
No objections, but I didn't work my way through this one as closely as I should have.

**Comment by tam203** [comment]
If I read this correctly the user/application attributes are no longer at a separate/object from the Zarr required ones. If this is indeed the case then I think that's a great step.

Good stuff @alimanfoo

**Comment by alimanfoo** [comment]
> No objections, but I didn't work my way through this one as closely as I should have.

Thanks, no problem, I think we can revisit this as many times as we want after merge to the 3.0 dev branch.

**Comment by alimanfoo** [comment]
> If I read this correctly the user/application attributes are no longer at a separate/object from the Zarr required ones. If this is indeed the case then I think that's a great step.

Cool, yes proposing that attributes are within the array and group metadata objects, not separate.

**Pull request merged**
