### PR TITLE
Use pydata-sphinx-theme

### PR DESCRIPTION
**Pull request by jrbourbeau**
This PR switches to using the [`pydata-sphinx-theme`](https://github.com/pandas-dev/pydata-sphinx-theme) Sphinx theme. This is totally subjective, but I do like the way this theme looks (see screenshot below). Curious to hear what others think. 

Screen Shot 2020-03-26 at 9 14 53 PM

### CODE REVIEW

**Comment by jakirkham** [comment]
Nice! I'm convinced 😄

cc @ryan-williams @joshmoore @alimanfoo (thoughts? 🙂)

**Comment by joshmoore** [comment]
vs. 
Screen Shot 2020-03-27 at 09 13 11

? Yeah, I'm in :)

As a side note, I'm willing to look into getting this branch to be the default view on readthedocs.

**Comment by alimanfoo** [comment]
Big :+1: :-)

**Comment by jrbourbeau** [comment]
Thanks for the feedback! Merging

> I'm willing to look into getting this branch to be the default view on readthedocs.

That'd be great. If you'd like, feel free to add me on readthedocs (username jrbourbeau) and I can also take a look

**Comment by joshmoore** [comment]
If you omit `latest` from RTD, it now redirects to https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/ to make it explicit. We may want to move `stable` to point at `master` and have `latest` point at `v3.0` or `dev` or whatever we will be using going down the road.

**Comment by alimanfoo** [comment]
> If you omit `latest` from RTD, it now redirects to https://zarr-specs.readthedocs.io/en/core-protocol-v3.0-dev/ to make it explicit. 

Thanks Josh.

> We may want to move `stable` to point at `master` and have `latest` point at `v3.0` or `dev` or whatever we will be using going down the road.

Yep, not sure what is the best approach until we have something stable.

**Comment by jakirkham** [comment]
Maybe we can disable `stable` from showing up or make `latest` the default or similar?

**Comment by alimanfoo** [comment]
> Maybe we can disable `stable` from showing up or make `latest` the default or similar?

Yeah, maybe `core-protocol-v3.0-dev` should be the default branch for the time being?

**Comment by alimanfoo** [comment]
...or disable `latest` altogether?

**Comment by joshmoore** [comment]
> Maybe we can disable stable from showing up or make latest the default or similar?

`latest` was the default this morning. Trying v3 now as the default.

> ...or disable latest altogether?

I deactivated `latest`, but it's still reachable, presumably because there was already a build?

**Comment by alimanfoo** [comment]
All looks good now, thanks Josh.

**Pull request merged**
