### PR TITLE
Intro edit

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has some edits to the introduction, to try to make the document as accessible as possible to a new reader.

In particular, I've tried to move some more technical matter regarding comparisons with v2 to the end, so the reader can start with a general introduction and motivation, then move into the concepts and protocol.

Comments welcome of course.

### CODE REVIEW

**Comment by alimanfoo** [comment]
cc @davidbrochart

**Comment by davidbrochart** [comment]
LGTM

**Review by Carreau — APPROVED** [review]

**Review by rabernat — APPROVED** [review]
These look like great suggestions.

Today I sat down to work on my review of v3, but then I noticed this. So I would prefer to merge this first.

**Comment by rabernat** [comment]
Apologies if I overstepped by merging this. Despite having read https://github.com/zarr-developers/zarr-specs/issues/101, I am not 100% clear on the process.

**Comment by jakirkham** [comment]
Seems fine to merge this. We can always do more PRs to refine things further 😄 It seems more important at this stage to get more people comfortable with merging here so we can improve our bandwidth a bit (especially as this work happens asynchronously) 😉

**Comment by rabernat** [comment]
That's what I'm trying to do! :)

**Pull request merged**
