### PR TITLE
remove implicit groups

### PR DESCRIPTION
**Pull request by d-v-b**
this PR removes support for implicit groups (Zarr groups with no metadata documentation) from the spec. See #291 for the motivation. Besides changing the content of the text, I don't know what else to change, so I'm keeping this a draft for now.

A mergeable version of this PR would include a section explaining what implicit groups are, why they were added previously, and why they are now removed. I am happy to add this if it looks like this PR has legs.

Related discussion: #184

### CODE REVIEW

**Comment by MSanKeys963** [comment]
@d-v-b, is this PR ready for review?

**Comment by d-v-b** [comment]
@MSanKeys963 yes!

**Comment by d-v-b** [comment]
how can we move forward with this? I think it's important to make these changes quickly, before we get skew between implementations.

**Comment by jhamman** [comment]
@zarr-developers/steering-council - this PR has sat without review for 4 months. Can we move it forward please?

**Review by jbms — DISMISSED** [review]

**Review by rabernat — APPROVED** [review]
Thanks for the push @jhamman.

**Comment by joshmoore** [comment]
@d-v-b: do you want to take a look at the conflict?

**Comment by d-v-b** [comment]
> @d-v-b: do you want to take a look at the conflict?

done!

**Comment by bjoernthiel** [comment]
@joshmoore Please add the following line directly after "Group metadata": 
Each Zarr group in a hierarchy must have a group metadata document, named zarr.json.

**Pull request merged**
