### PR TITLE
Restructure keys and remove entry-point metadata

### LINKED ISSUE #177: v3 core spec: Consider to drop /meta prefix, have file at URI
Citing @jbms from https://github.com/zarr-developers/zarr-specs/pull/149#discussion_r929356279:

> As discussed on the community meeting, this naming scheme has the drawback in that there is not a good way to have a path directly to a non-root array.  Additionally, it was noted that to better integrate with existing filesystem completion in editors, etc., it would be helpful if the path were a real filesystem path.
>
> A few proposals were made:
> 
> - Instead of `"meta/root" + P + ".group.json"` as the key for the metadata file, instead have it just be: `P + ".zr3"`.  This would lead to a key of just `".zr3"` for the root.  It was noted though that with a consolidated metadata extension these metadata files would not actually exist.  The data could be placed in e.g. "_data" or something, where names beginning with an underscore could be reserved to prevent conflicts.  This would still require a way to locate the root directory --- that could be done by storing the relative path inside the array metadata.
> - Alternatively, we could leave the directory structure alone but require an extension as part of the directory containing the root, e.g. "foo.zr3", and disallow any array or group names from ending in ".zr3".  Then you could use: "path/to/root.zr3/path/to/array" as a pseudo-path to an individual array.  The downside is that it may be confusing to use something that looks like a path, and where a portion corresponds to a real filesystem path but a portion does not.  File completion in editors also wouldn't support this.
> - We could use a special syntax to combine both a path to a root and a path to an array into a single string, e.g. "path/to/root//path/to/array" or "path/to/root#/path/to/array".  We would need to carefully choose the syntax to avoid conflicts with e.g. fsspec, and file completion in editors also wouldn't support this.

Some more comments from discussion rounds I remember:
* .json suffix is useful to have a correct mimetype by default for many stores, e.g. S3
* Having a URI (TBD, see #132) to an array or group, it would be great to actually find a directory or file there. E.g. `s3://bucket-name/key-name/name-of-the-zarr-path.zarr/hierarchy/path/my-data.array.json` could be a URI to point to the `my-data` array at the path `hierarchy/path/my-data` of the zarr hierarchy which is placed under `s3://bucket-name/key-name/name-of-the-zarr-path.zarr/`. (Just made up a URI here as an example, feel free to discuss this in #132). Using such a URI schema and dropping the `/meta` prefix, one could find the relevant file (at least for filesystem or http stores or using appropriate clients for other stores).
* The original motivation to have `/meta` and `/data` separate is to be able to list all meta keys without also listing the chunk files for efficiency reasons. If it's possible to exclude directories for key-listings for most relevant stores, only using a prefix for the chunk files would still give this efficiency, but it's unclear if that's the case.
* It might be useful to be able to place chunk-files in arbitrary locations (possibly even other stores). This could be added as an extension, but can also be considered for the core spec.

Pinging discussion participants I remember so far: @joshmoore @jbms @rabernat @WardF

### PR DESCRIPTION
**Pull request by jbms**
Fixes https://github.com/zarr-developers/zarr-specs/issues/192, fixes #177

### CODE REVIEW

**Review by rabernat — DISMISSED** [review]
I have reviewed this and think it looks all good.

Thanks for taking the time to write this down Jeremey.

**Review by jstriebel — DISMISSED** [review]
Thanks @jbms! Also LGTM, just pushed a commit with minor formatting edits. I also started to clean-up the Storage – Operations section, but noticed that it's quite out of date and probably better fixed in a separate PR. (We might even consider removing it completly, I'm not quite sure how helpful it is.)

**Comment by jstriebel** [comment]
@rabernat Could you approve this once again? my approval doesn't count since I commited and also my commit automatically discarded your previous one.

**Comment by jstriebel** [comment]
PS: A changelog entry is missing, could you add one @jbms?

**Review by joshmoore — APPROVED** [review]
:+1:

**Pull request merged**
